/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVRFCoordinatorV2Plus } from "./IVRFCoordinatorV2Plus";
export type { IVRFMigratableConsumerV2Plus } from "./IVRFMigratableConsumerV2Plus";
export type { IVRFSubscriptionV2Plus } from "./IVRFSubscriptionV2Plus";
