/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Lock } from "./Lock";
export type { NoLossLottery } from "./NoLossLottery";
