/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../../../../common";
import type {
  VRFV2PlusClient,
  VRFV2PlusClientInterface,
} from "../../../../../../../../@chainlink/contracts/src/v0.8/vrf/dev/libraries/VRFV2PlusClient";

const _abi = [
  {
    inputs: [],
    name: "EXTRA_ARGS_V1_TAG",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60fe610051600b82828239805160001a6073146044577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063f7514ab4146038575b600080fd5b603e6052565b6040516049919060af565b60405180910390f35b7f92fd13387c7fe7befbc38d303d6468778fb9731bc4583f17d92989c6fcfdeaaa81565b60007fffffffff0000000000000000000000000000000000000000000000000000000082169050919050565b60a9816076565b82525050565b600060208201905060c2600083018460a2565b9291505056fea264697066735822122002f8ee6578faf4bb6efc635a81fafdde8137f19d413ba3c2680c44aee69b451964736f6c634300081c0033";

type VRFV2PlusClientConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: VRFV2PlusClientConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class VRFV2PlusClient__factory extends ContractFactory {
  constructor(...args: VRFV2PlusClientConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      VRFV2PlusClient & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): VRFV2PlusClient__factory {
    return super.connect(runner) as VRFV2PlusClient__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): VRFV2PlusClientInterface {
    return new Interface(_abi) as VRFV2PlusClientInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): VRFV2PlusClient {
    return new Contract(address, _abi, runner) as unknown as VRFV2PlusClient;
  }
}
