/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IVRFCoordinatorV2Plus__factory } from "./IVRFCoordinatorV2Plus__factory";
export { IVRFMigratableConsumerV2Plus__factory } from "./IVRFMigratableConsumerV2Plus__factory";
export { IVRFSubscriptionV2Plus__factory } from "./IVRFSubscriptionV2Plus__factory";
