/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVRFMigratableConsumerV2Plus,
  IVRFMigratableConsumerV2PlusInterface,
} from "../../../../../../../../@chainlink/contracts/src/v0.8/vrf/dev/interfaces/IVRFMigratableConsumerV2Plus";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "vrfCoordinator",
        type: "address",
      },
    ],
    name: "CoordinatorSet",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "vrfCoordinator",
        type: "address",
      },
    ],
    name: "setCoordinator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVRFMigratableConsumerV2Plus__factory {
  static readonly abi = _abi;
  static createInterface(): IVRFMigratableConsumerV2PlusInterface {
    return new Interface(_abi) as IVRFMigratableConsumerV2PlusInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVRFMigratableConsumerV2Plus {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IVRFMigratableConsumerV2Plus;
  }
}
